version: "3"
services:
  apicore_comp:
    environment:
     - TZ=Asia/Shanghai
    container_name: apicore_comp
    build: ./ReportApi_Core
    ports: 
     - "9016:80"
  webcore_comp:
    environment:
     - TZ=Asia/Shanghai
    container_name: webcore_comp
    build: ./WebCore
    ports:
     - "9017:80"